apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs-container
          image: suzalshrestha/test:1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: LoadBalancer
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000